#!/usr/bin/env python3
"""Generate the Catppuccin target inventory from a pinned source checkout.

The source checkout is supplied explicitly by a maintainer.  Nix evaluation
only consumes the checked-in manifest; it never scans or fetches upstream.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path


SKIP = {"all-modules", "default"}
VSCODE_NAMES = ("vscode", "cursor", "vscodium", "windsurf", "kiro", "antigravity")


def entry(name: str, platform: str, source_text: str = "") -> dict:
    option_name = name
    option_path = ["catppuccin", option_name]
    complex_target = False
    renderer_kind = "simple"
    capabilities = {"accent": "none", "profiles": False}

    if name == "neovim":
        option_name = "nvim"
        option_path = ["catppuccin", option_name]
    elif name == "zed-editor":
        option_name = "zed"
    elif name == "gtk":
        option_path += ["icon"]
        capabilities["accent"] = "exact"
    elif name == "vscode":
        option_path = ["catppuccin", "vscode", "profiles", "default"]
        capabilities = {"accent": "exact", "profiles": True}
        complex_target = True
        renderer_kind = "vscode-profile"
    elif name == "firefox":
        option_path = ["catppuccin", "firefox", "profiles", "default"]
        capabilities = {"accent": "exact", "profiles": True}
        complex_target = True
        renderer_kind = "firefox-profile"
    elif name == "cursors":
        capabilities["accent"] = "exact"

    if "accentSupport = true" in source_text:
        capabilities["accent"] = "exact"

    if name not in {"neovim", "gtk", "vscode", "firefox", "cursors"}:
        option_path = ["catppuccin", option_name]

    return {
        "id": name,
        "optionPath": option_path,
        "platforms": [platform],
        "variants": "all",
        "accent": capabilities["accent"],
        "autoSafe": not complex_target,
        "trustTier": "official",
        "class": "complex" if complex_target else "simple",
        "profiles": capabilities["profiles"],
        "rendererKind": renderer_kind,
    }


def inventory(source: Path) -> dict:
    modules: dict[str, dict] = {}

    def add(name: str, platform: str, path: Path) -> None:
        if name in SKIP:
            return
        source_text = path.read_text(encoding="utf-8")
        for target_name in {
            "chrome": ("brave", "chromium", "vivaldi"),
            "gitea": ("gitea", "forgejo"),
        }.get(name, (name,)):
            item = entry(target_name, platform, source_text)
            current = modules.get(target_name)
            if current is None:
                modules[target_name] = item
            else:
                current["platforms"] = sorted(set(current["platforms"] + item["platforms"]))

    for platform, directory in (("homeManager", source / "modules/home-manager"), ("nixos", source / "modules/nixos"), ("darwin", source / "modules/darwin")):
        for path in sorted(directory.glob("*.nix")):
            add(path.stem, platform, path)

    for name in VSCODE_NAMES:
        if "vscode" in modules:
            item = dict(modules["vscode"])
            item["id"] = name
            item["optionPath"] = ["catppuccin", name, "profiles", "default"]
            item["class"] = "complex"
            item["profiles"] = True
            modules[name] = item
    return {
        "schema": "theme-broker.catppuccin-manifest/v1",
        "source": {
            "repository": "https://github.com/catppuccin/nix",
            "revision": "673f730d0fc8db3468c51575f1d3d777cc55e51f",
        },
        "targets": dict(sorted(modules.items())),
    }


def render(data: dict) -> str:
    def nix_list(values: list[str]) -> str:
        return "[" + " ".join(json.dumps(value) for value in values) + "]"

    lines = [
        "# Generated by native/catppuccin/generate-manifest.py; review source changes.",
        "{",
        f'  schema = "{data["schema"]}";',
        "  source = {",
        f'    repository = "{data["source"]["repository"]}";',
        f'    revision = "{data["source"]["revision"]}";',
        "  };",
        "  targets = {",
    ]
    for name, item in data["targets"].items():
        lines += [f"    {name} = {{"]
        lines.append(f'      id = "{item["id"]}";')
        lines.append(f'      optionPath = {nix_list(item["optionPath"])};')
        lines.append(f'      platforms = {nix_list(item["platforms"])};')
        lines.append(f'      variants = "{item["variants"]}";')
        lines.append(f'      accent = "{item["accent"]}";')
        lines.append(f'      autoSafe = {str(item["autoSafe"]).lower()};')
        lines.append(f'      trustTier = "{item["trustTier"]}";')
        lines.append(f'      class = "{item["class"]}";')
        lines.append(f'      profiles = {str(item["profiles"]).lower()};')
        lines.append(f'      rendererKind = "{item["rendererKind"]}";')
        lines.append("    };")
    lines += ["  };", "}", ""]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("source", type=Path, help="checked-out catppuccin/nix source")
    parser.add_argument("--output", type=Path, default=Path(__file__).with_name("manifest.nix"))
    args = parser.parse_args()
    if not (args.source / "modules").is_dir():
        parser.error(f"not a catppuccin/nix checkout: {args.source}")
    data = inventory(args.source)
    args.output.write_text(render(data), encoding="utf-8")
    print(f"wrote {args.output}: {len(data['targets'])} targets")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
